### PR TITLE
Create tree

### PR DESCRIPTION
**Pull request by maasencioh**
taking in mind that is a different function to the converter I didn't know how to deal with the worker

### CODE REVIEW

**Comment by targos** [comment]
I have no idea what this is but the test seems a little bit too simple

**Comment by lpatiny** [comment]
Worker does not matter, this is a fast function.

**Comment by maasencioh** [comment]
@lpatiny but for just handling the cases `##TITLE`, `##END` and `##DATATYPE` I think that LDR is just too much

**Comment by lpatiny** [comment]
It depends if we want to be general or not. It is completely correct to write

##DATA_TYPE =
##DATA TYPE=
## data type =

So I think we should have a function that just take care of normalizing all this. This could be a common fonction for both convert and tree.

**Pull request merged**
